[workspace]
members = [
    "ya-runtime-sdk-derive",
    "ya-runtime-sdk",
    "examples/*"
]

[patch.crates-io]
ya-runtime-api = { git = "https://github.com/golemfactory/yagna.git", rev = "862cc71361fb4ac6d438a93bb43dd472648bb51e", optional = true }
