[workspace]
members = [
    "ya-runtime-sdk-derive",
    "ya-runtime-sdk",
    "examples/*"
]

[patch.crates-io]
ya-runtime-api = { git = "https://github.com/golemfactory/yagna.git", rev = "2222cadeed58ecc44295092fcb0bc9ffba8a3722" }
