[package]
name = "ya-runtime-sdk"
description = "Facilitates creating new runtimes for Yagna"
version = "0.1.1"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"
license = "GPL-3.0"
homepage = "https://github.com/golemfactory/ya-runtime-sdk"
repository = "https://github.com/golemfactory/ya-runtime-sdk"

[features]
default = []
macros = ["ya-runtime-sdk-derive"]

[dependencies.ya-runtime-api]
version = "0.3"
features = ["codec"]
git = "https://github.com/golemfactory/yagna.git"
rev = "20e8da5a3d76321c2ac8ba2afe78706a0c478bd5"

[dependencies.ya-runtime-sdk-derive]
version = "0.1"
path = "../ya-runtime-sdk-derive"
optional = true

[dependencies]
anyhow = "1.0"
directories = "3.0"
futures = "0.3"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
structopt = "0.3"
tokio = { version = "0.2", features = ["blocking", "io-std", "io-util", "rt-core", "rt-threaded", "macros"] }
toml = "0.5"

[dev-dependencies]
tempdir = "0.3"
